sudo: false
services:
  - docker
git:
  depth: 150
language: ruby
bundler_args: --without development
before_install:
  - gem install bundler -v '< 2' --no-document;
before_script:
  - 'git config --global user.email "you@example.com"'
  - 'git config --global user.name "Your Name"'
script: "bundle exec $CHECK"
notifications:
  email: false

matrix:
  include:
    - stage: puppet-agent lint
      rvm: 2.1.7
      env: "CHECK='rubocop -D'"
    - stage: puppet-agent lint
      rvm: 2.1.7
      env: "CHECK='rake commits'"
    - stage: puppet-agent container tests
      language: generic
      script:
        - cd docker && make lint && make build && make test
